// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAnLUgMt_1H-E20RO4CgSz83I291ZxW6E',
    appId: '1:57281647344:web:af107c3a1de012d08d6835',
    messagingSenderId: '57281647344',
    projectId: 'gods-eye-1df04',
    authDomain: 'gods-eye-1df04.firebaseapp.com',
    storageBucket: 'gods-eye-1df04.appspot.com',
    measurementId: 'G-3L2PWRL0NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuLWIz5Z-4Uxf6ftsQk90QNDy1Igbaw5k',
    appId: '1:57281647344:android:91d1d7d9f61a6f6b8d6835',
    messagingSenderId: '57281647344',
    projectId: 'gods-eye-1df04',
    storageBucket: 'gods-eye-1df04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzhpF8Tu7shmwF61ERvzhHT7LLiLf0iRM',
    appId: '1:57281647344:ios:d2732773f9ec7ee48d6835',
    messagingSenderId: '57281647344',
    projectId: 'gods-eye-1df04',
    storageBucket: 'gods-eye-1df04.appspot.com',
    iosBundleId: 'com.gods.eye.godsEye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzhpF8Tu7shmwF61ERvzhHT7LLiLf0iRM',
    appId: '1:57281647344:ios:a9eaed29c24f86288d6835',
    messagingSenderId: '57281647344',
    projectId: 'gods-eye-1df04',
    storageBucket: 'gods-eye-1df04.appspot.com',
    iosBundleId: 'com.gods.eye.godsEye.RunnerTests',
  );
}
